# Guess The Number
# Write a program where the computer randomly generates a number between 0 and 20.
# The user needs to guess what the number is.
# If the user guesses wrong, tell them their guess is either too high, or too low.

import random

found = False
number = random.randint(1, 20)
half = int(number/2)
closer = int(number/4*3)

while not found:

    guess = int(input("Guess the number that's being generated by the Computer from 1 - 20: "))

    if guess == number:
        print("You're Correct")
        found = True
    elif guess < half:
        print("Your number is too low")
    elif guess > number:
        print("Your number is too high")
    elif guess > closer:
        print("You're getting closer")
    elif guess > half or guess <= closer:
        print("Your number is getting close")
